version: "3"

services:
  db:
    image: mariadb:10.10.2
    container_name: barbelDB
    ports:
      - 3306:3306
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - barbel_backend
    restart: always
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d

networks:
  barbel_backend: