spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbcUrl: jdbc:mariadb://productDB:3306/product?characterEncoding=UTF-8&serverTimezone=UTC
    username: barbel
    password: barbel!
  second-datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbcUrl: jdbc:mariadb://productDB_write:3309/product?characterEncoding=UTF-8&serverTimezone=UTC
    username: barbel
    password: barbel!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 4002