spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/product?characterEncoding=UTF-8&serverTimezone=UTC
    username: barbel
    password: barbel!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB